#!/usr/bin/python3
import sys

def print_lines(text,pos,n):

	out = ""
	for i in range(pos,n):
		out += text[i] + '\n'
	return out

def print_cols(text,pos,n):

	list_of_cols = []
	for x in text:
		list_of_cols.append(x.split())

	out = ""
	for i in range(len(list_of_cols)):
		for j in range(pos,len(list_of_cols[i])):
			out += list_of_cols[i][j] + ' '
		out += '\n'
	return out


'''
line 3 5
line "input.txt" 3 5
line "input.txt" -c 3 5
line "input.txt" -c 0 "key"
line "key" end
line "key1" "key2"
line -c "key1" "key2"
'''

def main():

    if type(argv[1] ==)
    file = open("input.txt",'r')
    text = file.read()
    file.close()
    text = text.split('\n')
    parser = argparse.ArgumentParser()
    
    parser.add_argument("-r",nargs=2,type=int)
    args = parser.parse_args()

'''
    if len(args.pos_args) == 2:
	    print("2 arguments")
    elif len(args.pos_args) == 1:
	    print("1 arg")
    else:
	    print("Missing argument")
	    
main()
